---
- name: Converge
  hosts: all
  become: true

  roles:
    - ansible-role-anaconda

  post_tasks:
    - name: Test that Anaconda python has been installed
      shell: "{{ anaconda_install_path }}anaconda{{ anaconda_python_version }}/bin/python -v -c 'quit();'"
      args:
        executable: /bin/bash
      register: python_version
      changed_when: false
      failed_when:
        - '"Anaconda, Inc." not in python_version.stderr'
