---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Test that Anaconda python has been installed
      command: "/opt/anaconda3/bin/python -v -c 'quit();'"
      register: python_version
      changed_when: false
      failed_when:
        - '"Anaconda, Inc." not in python_version.stderr'
